### ISSUE TITLE
Publish Cordova Plugin

### ISSUE THREAD

**Issue by herkulano** [RADAR-CNS/RADAR-Cordova-OpenSmile-Plugin#1]
@nivemaham @nithinth7 could you publish the plugin to the registry so that it can be easily installed in the Questionnaire App.

http://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/index.html#publishing-plugins

//cc @kerzmaximilian @afolarin

**Comment by hesamsagha** [comment]
The plugin is published. The name is cordova-plugin-opensmile.
